theme: jekyll-theme-cayman
title: Robin Cooper - Data Analyst
description: "A blog about Robin..."
baseurl: "https://www.linkedin.com/in/robin-sequeira-9aa132177/" # for test: remove string '/space-jekyll-template' to ''
url: "https://www.linkedin.com/in/robin-sequeira-9aa132177/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
url: "https://www.linkedin.com/in/robin-sequeira-9aa132177/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Robin Cooper
